build: false
platform:
  - x64

image: Visual Studio 2017

## Build matrix for lowest and highest possible targets
environment:
  RABBITMQ_VERSION: 3.7.17

## Cache CI dependencies
cache:
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
    - "%HOMEDRIVE%%HOMEPATH%"\packages" -> appveyor.yml

## Set up environment variables
init:
    - SET ANSICON=121x90 (121x90)

## Install PHP and composer, and run the appropriate composer command
install:
    - choco config set cacheLocation "%HOMEDRIVE%%HOMEPATH%"\packages
    # create same erlang cookie
    - ps: '[System.IO.File]::WriteAllText("C:\Users\appveyor\.erlang.cookie", "rabbitmq", [System.Text.Encoding]::ASCII)'
    - ps: '[System.IO.File]::WriteAllText("C:\Windows\System32\config\systemprofile\.erlang.cookie", "rabbitmq", [System.Text.Encoding]::ASCII)'
    - choco install rabbitmq -y --version=%RABBITMQ_VERSION%
    - refreshenv
    - cmd /c "C:\Program Files\RabbitMQ Server\rabbitmq_server-%RABBITMQ_VERSION%\sbin\rabbitmqctl.bat" ping -n rabbit@APPVYR-WIN
    - SET rabbitmq_version=%RABBITMQ_VERSION%
    - ps: Invoke-WebRequest "https://raw.githubusercontent.com/pika/pika/master/testdata/wait-rabbitmq.ps1" -OutFile "wait-rabbitmq.ps1"
    #- ps: .\wait-rabbitmq.ps1

## Run the actual test
test_script:
    - SET
    #- cmd /c "C:\Program Files\RabbitMQ Server\rabbitmq_server-%RABBITMQ_VERSION%\sbin\rabbitmqctl.bat" status -n rabbit@APPVYR-WIN
