build: false
platform:
  - x64

image: Visual Studio 2017

## Build matrix for lowest and highest possible targets
environment:
  ERTS_VERSION: erts-10.4
  RABBITMQ_VERSION: 3.7.17

## Cache CI dependencies
cache:
    - "%USERPROFILE%\\packages"

## Set up environment variables
init:
    - SET ANSICON=121x90 (121x90)

## Install PHP and composer, and run the appropriate composer command
install:
    - SET
    - choco config set cacheLocation "%USERPROFILE%\\packages"
    - ps: .\install.ps1

## Run the actual test
test_script:
    - SET
    - cmd /c "C:\Program Files\RabbitMQ Server\rabbitmq_server-%RABBITMQ_VERSION%\sbin\rabbitmqctl.bat" status -n rabbit@APPVYR-WIN
